engoo:
  api: https://engoo.co.kr/teachers/
  teachers:
    - 25420
    - 25817
    - 25215

telegram:
  myChatId: 237293953
  
tron:
  tokenTarget: TUW61yV5ptBeoRLSdf8bQUt6wREAaWKtQN
  trxTarget: TQLLiWzKg2Cu5hjywRSfPJYGhbPAkPNRUK