engoo:
  api: https://engoo.co.kr/teachers/
  teachers:
    - 25420
    - 25215

telegram:
  myChatId: 237293953
  
tron:
  trxTarget: TFmQQH14pMZhitALbKEZBDitKaMW3KX68B

firebase:
  databaseURL: 'https://marucool-f2bb1.firebaseio.com'